name: main

on:
  schedule:
    - cron: '*/9 * * * *'
  workflow_dispatch:

concurrency:
  group: testx
  cancel-in-progress: true

jobs:
  run-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 660

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          docker run \
            --cap-add=NET_ADMIN \
            --device=/dev/net/tun \
            igorotomo/disk
